### PR TITLE
Set lintr for linting R codes

### PR DESCRIPTION
**Pull request by eitsupi**
Addresses #169.

A series of fixes resolved all but one error.

```r
> lintr::lint_package()
.......................................
R/sanitize_code.R:25:1: style: [cyclocomp_linter] Functions should have cyclomatic complexity of less than 15, this has 16.
fill_block_comments <- function(lns, fill_with = " ") {
^
```

All errors can be corrected by refactoring the `fill_block_comments` function or allowing this in the rules.

- For objects used only as strings in `glue::glue` like functions, lintr is not detectable, so the `# nolint` comment has been used.
- `object_name_linter` was turned off because functions that mix underbars and dots are not allowed in lintr.
- `commented_code_linter` was turned off because there is quite a lot of code in the comments.

@Ilia-Kosenkov Sorry to I do this even though you are the assignee of #169. Feel free to edit this PR.

### CODE REVIEW

**Review by CGMossa — APPROVED** [review]
Mostly stylistic changes. So far so good to me.

**Comment by eitsupi** [comment]
> All errors can be corrected by refactoring the `fill_block_comments` function or allowing this in the rules.

Curiously, the last commit did not raise this error.
The lint workflow is now green.

**Comment by Ilia-Kosenkov** [comment]
By all means, feel free to take a shot at any issue, or create your own issues for discussion. No hard feelings here.
`fill_block_comment()` is indeed quite large, but it is the cost of not using any third-party parsers for rust code (and thus keeping the package purely R). It can be reworked for sure (and there are lots of typos in the comments that can be fixed). Let's open an issue for this and fix it separately.

Otherwise, great job! If you are ready, mark this PR as ready for review & I'll merge it

**Comment by eitsupi** [comment]
Thanks.
I think you can merge this as the work I can do seems to be complete.

**Pull request merged**
