### PR TITLE
Fix linter complaints

### PR DESCRIPTION
**Pull request by Ilia-Kosenkov**
- Fix spelling errors
- Refactor type checking code

### CODE REVIEW

**Comment by CGMossa** [comment]
I don't understand some of these changes... Why did you change that one function that had a `length` parameter?

**Review by JosiahParry — APPROVED** [review]
> I don't understand some of these changes... Why did you change that one function that had a `length` parameter?

This is just rearranging the internals of the function. I had similar qualms about defining a function inside of a function—just never took it upon myself to fix it. The change is purely cosmetic! 

These look good and address long standing typos as well!

**Comment by JosiahParry** [comment]
Was that the auto-merger?! That was fast :P

**Comment by Ilia-Kosenkov** [comment]
Yep, just refactoring. Extracted inner functions as they introduced too much complexity

**Pull request merged**
