### PR TITLE
test: enable tests on CRAN

### PR DESCRIPTION
**Pull request by eitsupi**
https://github.com/extendr/rextendr/pull/280#issuecomment-1559654027

### CODE REVIEW

**Comment by Ilia-Kosenkov** [comment]
Oh you are running ahead of me in this :) Did you try submitting it to CRAN-like runners?

**Comment by eitsupi** [comment]
> Oh you are running ahead of me in this :) Did you try submitting it to CRAN-like runners?

No.
So there is still a possibility of problems when submitting CRANs.

Particular attention should be paid to cases where files are generated by writing to the home directory, etc.

**Comment by Ilia-Kosenkov** [comment]
Can we submit it to r-hub or something similar?

**Comment by eitsupi** [comment]
Perhaps the results of the R-hub runs will be sent to the maintainer's email address?
Could you check out this branch and run `devtools::check_rhub()` to test it?

**Comment by eitsupi** [comment]
@Ilia-Kosenkov The R-hub builders seem to pass the test successfully.

**Review by Ilia-Kosenkov — APPROVED** [review]
Looks good, I am merging this if there are no objections.

**Pull request merged**
