### PR TITLE
add josiah p. as contributor

### PR DESCRIPTION
**Pull request by JosiahParry**
Per suggestion a PR to add myself as a contributor to rextendr based on recent PR.

### CODE REVIEW

**Comment by Ilia-Kosenkov** [comment]
Thank you for your **huge** contribution via #263!
Based on this, we believe you should be on the list of package authors as a contributor (at least for now). This was discussed on discord, fyi @yutannihilation

**Review by CGMossa — APPROVED** [review]
A power user becomes a ctb. What a good day for this project.

**Review by Ilia-Kosenkov — APPROVED** [review]

**Review by multimeric — APPROVED** [review]

**Comment by CGMossa** [comment]
Oh @yutannihilation your approval is missing, and I pressed merge button. I'm deeply sorry, I missed that your approval was still orange and not green.

**Comment by yutannihilation** [comment]
Oh, was my approval required? Sorry, I didn't recognize it. I thought you already reached the consensus on Discord and that mention to me is just for my information. Anyway, I have no concern on this.

**Pull request merged**
