### PR TITLE
Update snapshot for rlang 1.0.0

### LINKED ISSUE #172: Update snapshots when rlang 1.0.0 is released
I see this difference with the dev version of rlang. Probably we need to update the snapshot when the version is released on CRAN.

```
Failure (test-use_extendr.R:5:3): use_extendr() sets up extendr files correctly
Snapshot of code has changed:
    old                              | new                                 
[1] "Code"                           | "Code"                           [1]
[2] "  use_extendr()"                | "  use_extendr()"                [2]
[3] "Message <message>"              - "Message <rlang_message>"        [3]
[4] "  v Creating 'src/rust/src'."   | "  v Creating 'src/rust/src'."   [4]
[5] "  v Writing 'src/entrypoint.c'" | "  v Writing 'src/entrypoint.c'" [5]
[6] "  v Writing 'src/Makevars'"     | "  v Writing 'src/Makevars'"     [6]

Run `snapshot_accept('use_extendr')` if this is a deliberate change
```

### PR DESCRIPTION
**Pull request by yutannihilation**
Closes #172

### CODE REVIEW

**Comment by yutannihilation** [comment]
We need to wait for the rlang binary is available on RSPM. Hopefully, soon...

**Comment by malcolmbarrett** [comment]
I just got a failure for this over at usethis's GHA so it's probably ready!

**Comment by yutannihilation** [comment]
Oh, thanks for sharing! The last attempt in an hour ago was no luck on macOS and on Windows, but let's try again!

**Comment by malcolmbarrett** [comment]
Ah, I wasn't paying attention to the OS. I think it was linux that failed! So maybe not 😝

**Pull request merged**
