### PR TITLE
Add -lbcrypt

### PR DESCRIPTION
**Pull request by yutannihilation**
Close https://github.com/extendr/extendr/issues/339

As of v1.57.0, Rust requires bcrypt to use `BCryptGenRandom` (Before then, it used to work without bcrypt to support Windows XP).

c.f. https://github.com/rust-lang/rust/pull/84096

### CODE REVIEW

**Comment by yutannihilation** [comment]
I didn't notice this would affect the snapshot test. Sorry for my laziness...

**Comment by yutannihilation** [comment]
The failure on R-devel ubuntu runner looks unrelated to this change. Probably something related to line breaks is wrong on testthat's side. For example:

```
── Failure (test-knitr-engine.R:27:3): Snapshot test of knitr-engine ───────────
Snapshot of code has changed:
old[6:23] vs new[6:14]
  "  "
  "  "
  "  Basic use example:"
  "  "
+ "  library(rextendr)# create a Rust functionrust_function(\"fn add(a:f64, b:f64) -> f64 { a + b }\")# call it from Radd(2.5, 4.7)#> [1] 7.2"
  "  "
- "  ```r"
- "  library(rextendr)"
  "  "
- "  # create a Rust function"
- "  rust_function(\"fn add(a:f64, b:f64) -> f64 { a + b }\")"
- "  "
- "  # call it from R"
- "  add(2.5, 4.7)"
- "  #> [1] 7.2"
- "  ```"
- "  "
  "  The package also enables a new chunk type for knitr, `extendr`, which compiles and evaluates Rust code. For example, a code chunk such as this one:"
  "  ````markdown"
  "  ```{extendr}"
```

**Comment by Ilia-Kosenkov** [comment]
Should we perhaps fix snapshot test as well?

**Comment by yutannihilation** [comment]
What do you mean? As you can see, nothing is different except for that the result with R-devel is without line breaks.

Actually, it seems the latest version of testthat's snapshot feature is broken somehow, though I still don't understand the details...

https://github.com/r-lib/testthat/issues/1509

**Comment by yutannihilation** [comment]
Hmm, it seems our problem is not related to r-lib/testthat#1509...

**Comment by Ilia-Kosenkov** [comment]
> What do you mean? As you can see, nothing is different except for that the result with R-devel is without line breaks.

Sorry I was reading from my phone and did not realize what the actual problem with the snapshot was.
What would be our strategy? Allow this one to fail for now? I may be able to get a devel version installed locally and see what happens to snapshot tests' output.

**Comment by yutannihilation** [comment]
Ah, I see. Sorry I didn't describe the details in the above comment.

> What would be our strategy? Allow this one to fail for now?

I have no idea at the moment... Let me think.

**Comment by Ilia-Kosenkov** [comment]
@clauswilke, would appreciate your opinion as well.

**Comment by Ilia-Kosenkov** [comment]
Perhaps we can file an issue at `{testthat}`? We have a reproducible case, maybe they can help us?

**Comment by yutannihilation** [comment]
Here's a minimal reproducible example repo. It seems the problem is around `cat_file()`, which we implemented, so it might not be where testthat is responsible for.

https://github.com/yutannihilation/testTestthat

But, really weird thing is, if I switch the GitHub action setting to the latest [`check-pak`](https://github.com/r-lib/actions/blob/master/examples/check-pak.yaml), it won't fail. I have no idea. Both use `rcmdcheck::rcmdcheck()`, so I have no idea why the results are different...

**Comment by yutannihilation** [comment]
I'm still not sure about the root cause of the failure, but it seems the new workflow works so this pull request should be ready to merge. While we can keep investigating what was happening, things on R-devel changes fast, so I think it might not be worth the effort.

**Review by Ilia-Kosenkov — APPROVED** [review]
Perhaps we should indeed rely on r-tools to find dependencies and check package instead of doing it ourselves. LGTM, at least for now.

**Comment by yutannihilation** [comment]
I see, thanks. IMHO, if there's now warning using `-lbcrypt` with older Rust, we don't need to do anything, but we'll need to check. I'll file a new issue for this.

**Pull request merged**
