### PR TITLE
[DRAFT - feedback needed] Sync crate and R package versions 

### PR DESCRIPTION
**Pull request by JosiahParry**
This PR closes https://github.com/extendr/rextendr/issues/304 and is related to #228.

This draft creates two functions `use_version()` and `sync_version()`. 

- `sync_version()` will set the version of the Rust crate in `src` to match that in the `DESCRIPTION` file. 
- `use_version()` wraps `usethis::use_version()` and 1. calls `usethis::use_version()` to increment the package version and 2. syncs the version with `sync_version()` 

I personally think masking functions from usethis is a little questionable. I like the workflow of: 

- make some significant changes to a package
- usethis::use_version()
- sync_version()

Alternatively, we could change the name of `use_version()` to `increment_version()` to avoid namespace conflicts.

### CODE REVIEW

**Comment by JosiahParry** [comment]
CC @eitsupi I would like your eyes on this! I opted for `cargo-bump` since it is easier to use and isn't tied to actually publishing a crate.

**Comment by eitsupi** [comment]
> I opted for `cargo-bump` since it is easier to use and isn't tied to actually publishing a crate.

`cargo-bump` does not seem to be currently maintained and is not recommended to be used.

**Comment by JosiahParry** [comment]
Sure, thats fine. More importantly, though, is the user experience. Do you prefer masking usethis?

**Comment by eitsupi** [comment]
> Do you prefer masking usethis?

I would also prefer to update only Cargo.toml without wrapping the usethis function as you suggested.

**Pull request closed without merging**
