### PR TITLE
update SystemRequirements to match CRAN requirements

### PR DESCRIPTION
**Pull request by JosiahParry**
This PR is a follow up of #320 and a replication of #310 

In order for #320 to be successful the `SystemRequirements` field needs to match the CRAN requirement. This PR adjusts the field accordingly and updates the requisite tests.

### CODE REVIEW

**Comment by JosiahParry** [comment]
This should pass once #328 is merged

**Comment by Ilia-Kosenkov** [comment]
I assume this is also related to #104?

**Comment by JosiahParry** [comment]
Yeah, I think this would close it. Seeing new failures in CI

**Comment by JosiahParry** [comment]
Updated snaps. hopefully CI passes

**Review by Ilia-Kosenkov — APPROVED** [review]

**Pull request merged**
