### PR TITLE
feat!: set `SystemRequirements` field automatically

### PR DESCRIPTION
**Pull request by eitsupi**
Currently a message to notice this field (`Please update the system requirement in 'DESCRIPTION' file.`), but I do not think there is any disadvantage to setting it up automatically.

The notation `SystemRequirements: Cargo (rustc package manager)` has been used in `gifski`, `hellorust` etc.
https://github.com/cran/gifski/blob/8bc440a1e3921af1f37a0deb27a01b8274d9b138/DESCRIPTION#L16
https://github.com/cran/hellorust/blob/2265950f01f2bbd87bab26c4f242b9fa8c9817dc/DESCRIPTION#L17

### CODE REVIEW

**Comment by CGMossa** [comment]
Another great idea. However, this is a "cran" / free field, and could contain
a number of things. Some packages include that you need GNUMake to compile a package.

**Comment by eitsupi** [comment]
> However, this is a "cran" / free field, and could contain
> a number of things. Some packages include that you need GNUMake to compile a package.

Of course, I understand that and therefore will not overwrite it if `SystemRequirements` has already been set. This is as confirmed by the test.

**Comment by eitsupi** [comment]
Is there any reason this can't be merged?

**Review by Ilia-Kosenkov — APPROVED** [review]
LGTM, should I merge right now or do you have anything else to modify?

**Comment by eitsupi** [comment]
Thank you for your review. I think you can merge this one right away.

**Pull request merged**
