### PR TITLE
Add install instructions to `write_license_note()`

### LINKED ISSUE #281: Add install instructions to `write_license_note()`
I've just used `write_license_note()` for the first time. Wonderful function! As I used it, I found the error message helpful since I didn't have the `cargo-license` library installed. Then it dawned on me that it might be useful to also include the command to install the library for those who may not be as familiar. Perhaps the function can be modified to something like 

```r
cli::cli_abort(
  c(
    "The {.code cargo license} command is required to run the {.fun write_license_note} function.",
    "Please install cargo-license ({.url https://crates.io/crates/cargo-license}) first.",
    i = "Run {.code cargo install cargo-license} from your terminal"
  ),
  class = "rextendr_error"
)
```

### PR DESCRIPTION
**Pull request by JosiahParry**
This PR closes #281 

It adds a small note to cli_abort() to inform the user of how they would install cargo-license

### CODE REVIEW

**Comment by JosiahParry** [comment]
CI errors are unrelated to PR.

**Comment by Ilia-Kosenkov** [comment]
@JosiahParry , can we merge this?

**Comment by JosiahParry** [comment]
@Ilia-Kosenkov, I think so. When were the checks last ran? My only worry is breaking snapshots

**Comment by Ilia-Kosenkov** [comment]
I just fixed that in the previous PR, I suggest removing changes to tests altogether

**Comment by Ilia-Kosenkov** [comment]
Hm seems I cannot restart successful checks. Well, let's merge it. Do you have enough permissions right now to do that?

**Comment by JosiahParry** [comment]
I do! I can "squash and merge" 🙈

**Comment by JosiahParry** [comment]
Eeek!

**Pull request merged**
